# Generated by Django 6.0.7 on 2026-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Others', 'Others')], max_length=50),
        ),
    ]
